In [1]:
import numpy as np

In [2]:
x = np.array([3, 4, 5])
y = np.array([4, 9, 7])

In [3]:
x + y

array([ 7, 13, 12])

In [4]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [5]:
x.ndim

2

In [6]:
x.dtype

dtype('int64')

In [7]:
np.array([[1, 2], [3.0, 4]]).dtype

dtype('float64')

In [8]:
np.array([[1, 2], [3, 4]], float).dtype

dtype('float64')

In [9]:
x.shape

(2, 2)

In [10]:
x.sum()

10

In [11]:
x = np.array([1, 2, 3, 4, 5, 6])
print('beginning x:\n', x)
x_reshape = x.reshape((2, 3))
print('reshaped x:\n', x_reshape)

beginning x:
 [1 2 3 4 5 6]
reshaped x:
 [[1 2 3]
 [4 5 6]]


In [12]:
x_reshape[0, 0]

1

In [13]:
x[2]

3

In [14]:
x_reshape[1, 1] = 2
x_reshape

array([[1, 2, 3],
       [4, 2, 6]])

In [15]:
x

array([1, 2, 3, 4, 2, 6])

In [16]:
my_tuple = (3, 4, 5)
my_tuple[0] = 2

TypeError: 'tuple' object does not support item assignment

In [17]:
x_reshape.shape

(2, 3)

In [18]:
x_reshape.T

array([[1, 4],
       [2, 2],
       [3, 6]])

In [23]:
x = np.sqrt(x)
x

array([1.        , 1.18920712, 1.31607401, 1.41421356, 1.18920712,
       1.56508458])

In [24]:
x_reshape

array([[1, 2, 3],
       [4, 2, 6]])

In [25]:
x**2

array([1.        , 1.41421356, 1.73205081, 2.        , 1.41421356,
       2.44948974])

In [26]:
x**0.5

array([1.        , 1.09050773, 1.14720269, 1.18920712, 1.09050773,
       1.2510334 ])

In [28]:
x = np.random.normal(size=50)
x

array([-0.13597803, -0.84186791, -0.05057074, -0.33795265, -1.15054023,
       -0.15092621, -0.47485029, -0.02278303, -0.65773042,  2.17864979,
        1.0138946 , -0.29015121, -0.74555152,  0.55035682, -0.21241384,
        1.55416438,  0.00658504,  1.60812004, -0.16776696, -0.68177057,
        0.69764816, -1.65725822, -1.28305745, -0.92673044,  0.01866527,
       -0.66103296, -0.30243297,  0.72329619, -0.31106752,  0.7188124 ,
       -0.7761753 , -0.24306716,  0.94425226,  0.0674745 , -2.84639967,
        0.16285214,  0.0826473 ,  1.59492797,  0.26746472,  1.20505253,
        0.23358998,  0.83063074, -0.13483556,  0.86350393, -1.68135832,
       -0.39660703, -0.18596717,  0.03896921, -1.21023343, -0.28326887])

In [29]:
y = x + np.random.normal(loc=50, scale=1, size=50)
y

array([49.91017635, 49.81227055, 49.24865043, 49.84113948, 49.14477435,
       49.52939106, 48.45201128, 49.25428458, 48.75344268, 52.28207812,
       50.28988433, 49.98741917, 49.46429053, 49.39201247, 51.12188313,
       50.82067425, 50.20141379, 52.97497321, 50.91103941, 49.35595414,
       50.9980221 , 48.07299834, 47.52725271, 49.11102817, 50.73511583,
       47.1332715 , 50.19363744, 50.85448571, 48.66940961, 50.23430056,
       48.70538821, 50.21893521, 50.80386906, 49.91117035, 47.0193115 ,
       49.33073273, 47.71746719, 51.01721366, 49.75251045, 52.2399132 ,
       50.32983444, 51.48455874, 48.17710641, 50.03006716, 48.12550105,
       49.04999675, 49.24234524, 49.9040591 , 49.24458951, 47.38082598])

In [30]:
np.corrcoef(x, y)

array([[1.        , 0.76462268],
       [0.76462268, 1.        ]])

In [31]:
rng = np.random.default_rng(1303)
print(rng.normal(scale=5, size=2))
rng2 = np.random.default_rng(1303)
print(rng2.normal(scale=5, size=2))

[ 4.09482632 -1.07485605]
[ 4.09482632 -1.07485605]


In [32]:
np.mean(y), y.mean()

(49.67925362454461, 49.67925362454461)

In [33]:
np.var(y), y.var(), np.mean((y - y.mean())**2)

(1.6606202814643667, 1.6606202814643667, 1.6606202814643667)

In [34]:
np.sqrt(np.var(y)), np.std(y)

(1.2886505660823522, 1.2886505660823522)

In [35]:
X = rng.standard_normal((10, 3))
X

array([[-2.03072919,  0.22681229, -0.82806113],
       [-0.94971965,  0.09748025,  1.13071035],
       [-0.503177  , -1.6146684 , -0.51143783],
       [ 1.30857567, -0.60106271, -1.04358358],
       [-0.77787108, -0.03621124, -2.366124  ],
       [-0.12532525, -1.04473968, -0.46412883],
       [ 0.33555586, -0.11933931, -0.19707608],
       [-0.35307465,  0.09562671,  0.83201011],
       [ 1.78919398, -3.25891725,  1.06043415],
       [-0.69168156, -1.16488556,  0.99099849]])

In [36]:
X.mean(axis=0)

array([-0.19982529, -0.74199049, -0.13962583])

In [37]:
X.mean(0)

array([-0.19982529, -0.74199049, -0.13962583])